version: '2'
services:

  mallcloud-mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mallcloud@1234
      MYSQL_DATABASE: mallcloud
    networks:
      - mallcloud

  mallcloud-redis:
    build:
      context: ./
      dockerfile: Dockerfile-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /data/redis:/data
    networks:
      - mallcloud

networks:
  mallcloud:
